--Using sub-queries

--1.
SELECT NAME, PHONE_NO, CUST_NO FROM CUSTOMER
WHERE CUST_NO = (SELECT CUST_NO FROM DEPOSITOR WHERE ACCOUNT_NO = 'A0004');


--2.
SELECT NAME FROM CUSTOMER
WHERE CUST_NO NOT IN (SELECT CUST_NO FROM LOAN);


--3.
SELECT BRANCH_CITY FROM BRANCH
WHERE BRANCH_CODE = (SELECT BRANCH_CODE FROM LOAN WHERE CUST_NO = (SELECT CUST_NO FROM CUSTOMER WHERE NAME = 'ASLESHA TIWARI'));


--4.
SELECT INST_NO, LOAN_NO, INST_AMOUNT FROM INSTALLMENT
WHERE LOAN_NO IN (SELECT LOAN_NO FROM LOAN WHERE CUST_NO = (SELECT CUST_NO FROM CUSTOMER WHERE NAME = 'ANKITA SINGH'));


--5.
SELECT BRANCH_NAME, BRANCH_CITY FROM BRANCH
WHERE BRANCH_CODE IN (SELECT BRANCH_CODE FROM ACCOUNT WHERE ACCOUNT_NO IN (SELECT ACCOUNT_NO FROM DEPOSITOR WHERE CUST_NO = (SELECT CUST_NO FROM CUSTOMER WHERE NAME = 'ABHIJIT MISHRA')));


--6.
SELECT ACCOUNT_NO FROM ACCOUNT
WHERE BALANCE > SOME (SELECT BALANCE FROM ACCOUNT WHERE TYPE = 'FD');


--7.
SELECT ACCOUNT_NO FROM ACCOUNT
WHERE BALANCE > ALL (SELECT BALANCE FROM ACCOUNT WHERE TYPE = 'FD');


--8.
SELECT * FROM BRANCH
WHERE EXISTS (SELECT 1 FROM LOAN WHERE BRANCH.BRANCH_CODE = LOAN.BRANCH_CODE);


--9.
SELECT * FROM LOAN
WHERE NOT EXISTS (SELECT 1 FROM INSTALLMENT WHERE LOAN.LOAN_NO = INSTALLMENT.LOAN_NO);


--10.
UPDATE ACCOUNT SET BALANCE = BALANCE * (CASE WHEN BALANCE > 80000 THEN 1.06 ELSE 1.05 END);


--Using Join

--1.
SELECT LOAN.LOAN_NO FROM LOAN
JOIN BRANCH ON LOAN.BRANCH_CODE = BRANCH.BRANCH_CODE
WHERE BRANCH.BRANCH_CITY = 'MUMBAI';


--2.
SELECT DISTINCT ACCOUNT.TYPE FROM ACCOUNT
JOIN BRANCH ON ACCOUNT.BRANCH_CODE = BRANCH.BRANCH_CODE
WHERE BRANCH.BRANCH_CITY = 'DELHI';


--3.
SELECT CUSTOMER.NAME, CUSTOMER.PHONE_NO FROM CUSTOMER
JOIN DEPOSITOR ON CUSTOMER.CUST_NO = DEPOSITOR.CUST_NO
JOIN ACCOUNT ON DEPOSITOR.ACCOUNT_NO = ACCOUNT.ACCOUNT_NO
WHERE ACCOUNT.BALANCE > 100000;


--4.
SELECT INSTALLMENT.INST_NO, INSTALLMENT.INST_AMOUNT FROM INSTALLMENT
JOIN LOAN ON INSTALLMENT.LOAN_NO = LOAN.LOAN_NO
JOIN CUSTOMER ON LOAN.CUST_NO = CUSTOMER.CUST_NO
WHERE CUSTOMER.NAME = 'RAJ ANAND SINGH';


--5.
SELECT DISTINCT CUSTOMER.NAME FROM CUSTOMER
WHERE CUST_NO NOT IN (SELECT CUST_NO FROM DEPOSITOR WHERE ACCOUNT_NO IN (SELECT ACCOUNT_NO FROM ACCOUNT WHERE TYPE = 'SB'));


--6.
SELECT DISTINCT CUSTOMER.NAME FROM CUSTOMER
JOIN LOAN ON CUSTOMER.CUST_NO = LOAN.CUST_NO
JOIN INSTALLMENT ON LOAN.LOAN_NO = INSTALLMENT.LOAN_NO
WHERE INSTALLMENT.INST_AMOUNT = 50000;


--7.
SELECT DISTINCT CUSTOMER.PHONE_NO FROM CUSTOMER
JOIN DEPOSITOR ON CUSTOMER.CUST_NO = DEPOSITOR.CUST_NO
JOIN ACCOUNT ON DEPOSITOR.ACCOUNT_NO = ACCOUNT.ACCOUNT_NO
JOIN BRANCH ON ACCOUNT.BRANCH_CODE = BRANCH.BRANCH_CODE
WHERE BRANCH.BRANCH_NAME = 'SALTLAKE BRANCH';


--8.
SELECT DISTINCT BRANCH.BRANCH_NAME, BRANCH.BRANCH_CITY FROM BRANCH
JOIN ACCOUNT ON BRANCH.BRANCH_CODE = ACCOUNT.BRANCH_CODE
JOIN DEPOSITOR ON ACCOUNT.ACCOUNT_NO = DEPOSITOR.ACCOUNT_NO
JOIN CUSTOMER ON DEPOSITOR.CUST_NO = CUSTOMER.CUST_NO
WHERE CUSTOMER.NAME = 'ABHIJIT MISHRA';


--9.
SELECT ACCOUNT.TYPE, ACCOUNT.BALANCE FROM ACCOUNT
JOIN DEPOSITOR ON ACCOUNT.ACCOUNT_NO = DEPOSITOR.ACCOUNT_NO
JOIN CUSTOMER ON DEPOSITOR.CUST_NO = CUSTOMER.CUST_NO
WHERE CUSTOMER.NAME = 'SWAROOP RAY';


--10.
WITH TotalBalancePerBranch AS(SELECT BRANCH_CODE, SUM(BALANCE) AS TotalBalance FROM ACCOUNT GROUP BY BRANCH_CODE),
AverageTotalBalance AS (SELECT AVG(TotalBalance) AS AvgTotalBalance FROM TotalBalancePerBranch)
SELECT BRANCH_CODE FROM TotalBalancePerBranch
WHERE TotalBalance > (SELECT AvgTotalBalance FROM AverageTotalBalance);
